### ISSUE TITLE
Invalid Link in add_a_source_item_with_specific_item_type.md

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/VSProjectSystem#32]
Invalid links in the document https://github.com/Microsoft/VSProjectSystem/blob/master/doc/automation/add_a_source_item_with_specific_item_type.md

These defaults can be augmented.

2.Automatically add the item to Solution Explorer, DTE, and raise other appropriate events if indeed the item you're adding has an item type that belongs to the set of source item types.

Showing link for https://github.com/Microsoft/VSProjectSystem/blob/master/doc/automation/custom_item_types.md

**Comment by adrianvmsft** [comment]
Thanks for reporting this issue. It's fixed now.

**Comment by shaggygi** [comment]
@adrianvmsft Thanks for updating, but the first link mentioned still appears to be broken.

These defaults can be augmented

It looks like it also points to the original broken link (the one that included doc/automation/***.md).

I'm assuming both links are supposed to point to the same place, but not sure?

Thanks again for looking into the issue.

**Comment by adrianvmsft** [comment]
You're right, I didn't notice that there were 2 links.
I fixed the other one as well.
Thanks!
